image: amazonlinux:2

stages:
  - terraform_apply
  - terraform_destroy

before_script:
  - yum install -y yum-utils unzip

  - if ! command -v aws &> /dev/null; then
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      ./aws/install -i /usr/local/bin -b /usr/local/bin;
    fi

  - if ! command -v terraform &> /dev/null; then
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo;
        yum install -y terraform;
      fi 
      
  - echo " installation done"
  - aws --version
  - terraform --version
  - echo " configuring aws credentials"

  - |
     if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
      elif [[ $CI_COMMIT_BRANCH == "prod" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
      else
        echo "no valide aws credentials for this branch"
      fi
    

  - aws sts get-caller-identity

.terraform_template:
  script:
   - cd $TF_DIR
   - aws configure set region $AWS_DEFAULT_REGION  
   - terraform init 
   - terraform validate

deploy_dev_1:
  stage: terraform_apply
  extends: .terraform_template
  variables: 
    TF_DIR: dev/region1
  script:
    - terraform plan -out=tfplan 
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - main

deploy_dev_2:
  stage: terraform_apply
  extends: .terraform_template
  variables: 
    TF_DIR: dev/region2
  script:
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - main

deploy_prod_1:
  stage: terraform_apply
  extends: .terraform_template
  variables: 
    TF_DIR: prod/region1
  script: 
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  when: manual  
  only:
    - prod

deploy_prod_2:
  stage: terraform_apply
  extends: .terraform_template
  variables: 
    TF_DIR: prod/region2
  script:
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - prod

destroy_dev_1:
  stage: terraform_destroy
  extends: .terraform_template     
  variables:
    TF_DIR: dev/region1
  script:
    - terraform plan -destroy -out=tfplan
    - terraform destroy -auto-approve
  when: manual
  only:
    - main 

destroy_dev_2:
  stage: terraform_destroy
  extends: .terraform_template
  variables:
    TF_DIR: dev/region2
  script:
    - terraform plan -destroy -out=tfplan
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
