image: amazonlinux:2

stages:
  - terraform_apply
  - terraform_destroy

before_script:
  - yum install -y yum-utils unzip

  - if ! command -v aws &> /dev/null; then
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      ./aws/install -i /usr/local/bin -b /usr/local/bin;
    fi

  - if ! commad -v terraform &> /dev/null; then
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo;
        yum install -y terraform;
      fi 

  - |
     if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
        export TF_DIR="dev/region-1, dev/region-2"

      elif [[ $CI_COMMIT_BRANCH == "prod" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
        export TF_DIR="prod/region-1,prod/region-2"
      else
        echo "no valide aws credentials for this branch"
      fi
  - aws sts get-caller-identity

.terraform_template:
  script:
   - cd $TF_DIR
   - aws configure set region $AWS_DEFAULT_REGION  
   - terraform init 
   - terraform validate

deploy_region_1:
  stage: terraform_apply
  extends: .terraform_template
  script:
    - terraform plan -out=tfplan 
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - main
    - prod
deploy_region_2:
  stage: terraform_apply
  extends: .terraform_template
  script:
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - main
    - prod

destroy_region_1:
  stage: terraform_destroy
  extends: .terraform_template     
  script:
    - terraform plan -destroy -out=tfplan
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
    - prod  

destroy_region_2:
  stage: terraform_destroy
  extends: .terraform_template
  script:
    - terraform plan -destroy -out=tfplan
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
    - prod
