image: amazonlinux:2

stages:
  - terraform_apply
  - terraform_destroy

before_script:
  - yum install -y yum-utils unzip

  - if ! command -v aws &> /dev/null; then
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      ./aws/install -i /usr/local/bin -b /usr/local/bin;
    fi

  - if ! command -v terraform &> /dev/null; then
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo;
        yum install -y terraform;
      fi 

  - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
        
      elif [[ $CI_COMMIT_BRANCH == "prod" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
      else
        echo "no valide aws credentials for this branch"
      fi

.terraform_template:
  script:
   - cd $TF_DIR
   - aws configure set region $AWS_DEFAULT_REGION  
   - terraform init 
   - terraform validate
   - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan

.terraform_destroy_template:
   extends: .terraform_te,plate
   script:
    - cd $TF_DIR
    - terraform plan -destroy -out=tfplan
    - terrafor destroy -auto-approve


deploy:
  stage: tarraform_apply
  extends: .terraform_template
  parallel:
      matrix:
        - TF_DIR: ["dev/region1", "dev/region2"]
          BRANCH: "main"
        - TF_DIR: ["prod/region1", "prod/region2"]  
          BRANCH: "prod"
  variables:
     TF_DIR: $TF_DIR
  when: manual
  only:
    - $BRANCH

destroy:
  stage: terraform_destroy
  extends: .terraform_destroy_template
  parallel:
      matrix:
        - TF_DIR: ["dev/region1", "dev/region2"]
          BRANCH: "main"
        - TF_DIR: ["prod/region1", "prod/region2"]  
          BRANCH: "prod"
  variables:
      TF_DIR: $TF_DIR
  when: manual
  only:
      - $BRANCH


